# Generated by Django 4.0.3 on 2022-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayPal', '0005_remove_order_post_order_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
