# Generated by Django 4.0.3 on 2022-06-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PayPal', '0008_order_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
