# Generated by Django 4.0.3 on 2022-06-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIComp', '0001_initial'),
        ('PayPal', '0009_rename_year_in_school_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post',
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APIComp.post'),
        ),
    ]
