# Generated by Django 4.0.3 on 2022-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIComp', '0001_initial'),
        ('PayPal', '0010_remove_order_post_order_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post',
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.ManyToManyField(to='APIComp.post'),
        ),
    ]
